name: ci

on:
  push:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set Repo DOCKER_IMAGE_VERSION Var to Branch Name
        run: |
          gh variable set DOCKER_IMAGE_VERSION --body "${{ github.ref_name }}"
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: elblag91/ziti-k8s-agent:${{ vars.DOCKER_IMAGE_VERSION }}
 